plugins {
    id 'java'
    id 'org.jastadd'
}

// Tracing enabled via `-Ptracing`
def tracing    = project.hasProperty('tracing')
// Can specify `-Ptracing=all` to select specific tracing levels, otherwise we use the default
def traceFlags = project.findProperty('tracing') ?: rootProject.jastaddTracingDefault
def jarName    = tracing ? 'intraj-tracing.jar' : 'intraj.jar'

def extraOpts = rootProject.extraOptions
if (!project.hasProperty('evaluator') || !project.findProperty('evaluator').equals("BasicStacked")) {
  extraOpts += "--dncConfig=${rootProject.file(rootProject.cacheConfigFile).absolutePath}"
}
if (tracing) {
    extraOpts += "--tracing=${traceFlags}".toString()
}

rootProject.ext.makeJastAddPass(project, rootProject, jarName,
                                extraOpts,
                                true) // index for top-level language server
afterEvaluate {
    tasks.named('generateAst') {
        dependsOn ':generateCacheConfig'
    }
}
