name: IntraJ Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    permissions:
      contents: read
    steps:
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'zulu'

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build and test
        run: ./gradlew clean build
